cognizant-softvision/donate-to

src/DonateTo.WebApi/DonateTo.WebApi.csproj
src/DonateTo.WebApi/Startup.cs
src/DonateTo.WebApi/Swagger/SwaggerExtensions.cs
src/DonateTo.WebApi/Swagger/SwaggerOptions.cs
src/DonateTo.WebApi/V1/Controllers/SampleController.cs

Adding Swagger and a sample controller which will be removed when we create the first one.
Let me know if i'm missing something in the SampleController that we need to add or change.

Adding Swagger and a Sample Controller

---

src/DonateTo.WebApplication/ClientApp/package.json
src/DonateTo.WebApplication/ClientApp/src/tsconfig.app.json
src/DonateTo.WebApplication/ClientApp/tsconfig.json

- Enabled ivy. 
- Changed husky lint using prod flag. 
- Excluded environments flag on build warning

Fix Angular build

---

src/DonateTo.IdentityServer/appsettings.Development.json
src/DonateTo.IdentityServer/appsettings.json
src/DonateTo.WebApi/appsettings.json
src/DonateTo.WebApplication/ClientApp/src/app/donation/components/donation/list/donation-list.component.html

web api configuration issue fixed

---

azure-pipeline-webapi.yml

Update azure-pipeline-webapi.yml for Azure Pipelines

---

azure-pipeline-webapplication.yml

enabled test for webapplication

Update azure-pipeline-webapplication.yml for Azure Pipelines

---

src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json
src/DonateTo.WebApplication/ClientApp/src/app/donation/components/donation/list/donation-list.component.html

No entries in english missing
Changed "Name" to "Product"

Bugfix resolved

---

src/DonateTo.ApplicationCore/Entities/Organization.cs
src/DonateTo.ApplicationCore/Entities/User.cs
src/DonateTo.ApplicationCore/Entities/UserOrganizations.cs
src/DonateTo.ApplicationCore/Interfaces/Services/IOrganizationService.cs
src/DonateTo.ApplicationCore/Interfaces/Services/IUserService.cs
src/DonateTo.IdentityServer/Data/EntityFramework/DonateIdentityDbContext.cs
src/DonateTo.IdentityServer/Services/ProfileService.cs
src/DonateTo.Infrastructure/Data/EntityFramework/DonateToDbContext.cs
src/DonateTo.Infrastructure/Data/Migrations/20200618190032_AddedUserOrganizationsRelation.Designer.cs
src/DonateTo.Infrastructure/Data/Migrations/20200618190032_AddedUserOrganizationsRelation.cs
src/DonateTo.Infrastructure/Data/Repositories/UserRepository.cs
src/DonateTo.Services/Extensions/ServiceCollectionExtension.cs
src/DonateTo.Services/Services/OrganizationService.cs
src/DonateTo.Services/Services/UserService.cs
src/DonateTo.WebApi/V1/Controllers/OrganizationController.cs

Add UserOrganizations Entity
Add GetOrganizations UserService
Add GetOrganizationsAsync UserService
Add AddedUserOrganizationsRelation

Add User Organizations Claims

---

src/DonateTo.IdentityServer/Dockerfile
src/DonateTo.IdentityServer/DonateTo.IdentityServer.csproj
src/DonateTo.IdentityServer/Styles/package-lock.json
src/DonateTo.IdentityServer/Styles/package.json

Fix for build in docker images, and added condition to avoid npm build step if npm is not available

Fix npm install in case its not installed

---

src/DonateTo.IdentityServer/Controllers/AccountController.cs
src/DonateTo.IdentityServer/Views/Account/ConfirmEmail.cshtml

This PR should resolved bugs #267 and #225

User is redirect to Signed Up page when login after registration

---

azure-pipeline-identityserver.yml

Update azure-pipeline-identityserver.yml for Azure Pipelines

---

azure-pipelines-qa.yml

Update azure-pipelines-qa.yml for Azure Pipelines

---

azure-pipelines-identity-qa.yml

Update azure-pipelines-identity-qa.yml for Azure Pipelines

---

src/DonateTo.WebApplication/ClientApp/src/app/donation/components/donation/list/donation-list.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/my-donations/my-donation.sandbox.ts
src/DonateTo.WebApplication/ClientApp/src/app/shared/store/donation/reducer.ts

After donation edit, user is redirected to my-donations
AB419

Bugfix - Donation Edit 

---

src/DonateTo.WebApplication/ClientApp/src/environments/environment.staging.ts

Change qa environments

---

src/DonateTo.WebApplication/ClientApp/src/app/admin/priority-questions/question-create/questions-create.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/priority-questions/question-create/questions-create.component.ts

This PR fix error of **tickets 441** "All fields appears as unfilled and mandatory when user edits a priority question" and **ticket 439** "Radio, Checkbox and Dropdown buttons overlaps in Priority Questions"

AB#441 AB#439 All fields appears as unfilled and mandatory when user edits a priority question

---

src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json
src/DonateTo.WebApplication/ClientApp/src/app/admin/priority-questions/question-create/questions-create.component.html
src/DonateTo.WebApplication/ClientApp/src/app/shared/containers/layout/admin-layout/admin-layout-routing.module.ts
src/DonateTo.WebApplication/ClientApp/src/app/shared/containers/layout/admin-layout/admin-layout.component.ts

Change Organizations to plural & Fix Url Paths

---

src/DonateTo.Services/Services/BaseService.cs
src/DonateTo.Services/Services/DonationRequestService.cs
src/DonateTo.Services/Services/OrganizationService.cs
src/DonateTo.Services/Services/QuestionService.cs
src/DonateTo.Services/Services/UserService.cs

Added case sensitive query support on predicates search

---

src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations-create/donations-create.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations-detail/donations-detail.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations-detail/donations-detail.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations-form/donations-form.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations-routing.module.ts
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.component.css
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.module.ts

[AB#472](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/472)

Applied UX suggested changes for Admin-Donations section

---

src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json

[AB#492](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/492)

Changed finish date to finish deadline

---

src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations-priority/donations-priority.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations-priority/donations-priority.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.module.ts

Donations requests  table is updated when is a new donation is created

Fixed priority questions blocking creation of a donation request.

---

src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json
src/DonateTo.WebApplication/ClientApp/src/app/admin/questions/question-create/questions-create.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/questions/question-create/questions-create.component.ts

AB#479 Added existOrder validation to form

---

src/DonateTo.WebApplication/DonateTo.WebApplication.csproj

npm run build:stage => npm run build:staging

Change QA working Directory Command

---

src/DonateTo.WebApi/V1/Controllers/DonationRequestController.cs

AB#638 Organization role throws 401 error

---

src/DonateTo.ApplicationCore/Models/Filtering/DonationRequestFilterModel.cs
src/DonateTo.Services/Services/DonationRequestService.cs
src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/donations/donations.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/shared/async-services/http/donation-request.service.ts
src/DonateTo.WebApplication/ClientApp/src/app/shared/models/filters/donation-request-filter.ts

[AB#637](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/637)

Added filter by organization name in Donation Request

---

src/DonateTo.WebApplication/ClientApp/src/app/home/components/donation-request/detail/donation-request-detail.component.html

[AB#612](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/612)

Fixed resources needed quantity

---

src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json
src/DonateTo.WebApplication/ClientApp/src/app/admin/organization/organization-detail/organization-detail.component.html
src/DonateTo.WebApplication/ClientApp/src/app/admin/organization/organization-form/organization-form.component.ts

[AB#640](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/640)

Changed "Contact" label to "Owner"

---

src/DonateTo.WebApplication/ClientApp/src/app/admin/questions/question-create/questions-create.component.ts

[AB#619](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/619)

Resolved validation error in range for question of type question

---

src/DonateTo.WebApplication/ClientApp/src/app/shared/components/nav-menu/nav-menu.component.less
src/DonateTo.WebApplication/ClientApp/src/styles.less

[AB#593](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/593)

Align navigation bar

---

src/DonateTo.WebApplication/ClientApp/src/app/admin/questions/question-create/questions-create.component.less

[AB#647](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/647)

Hidden delete button on questions

---

src/DonateTo.WebApplication/ClientApp/src/app/shared/components/nav-menu/nav-menu.component.less

[AB#653](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/653)

Language buttons aligned

---

src/DonateTo.Infrastructure/Data/Repositories/DonationRepository.cs

[AB#538](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/538)

Fixed wrong lambda expression

---

src/DonateTo.WebApplication/ClientApp/i18n/en.json
src/DonateTo.WebApplication/ClientApp/i18n/es.json
src/DonateTo.WebApplication/ClientApp/src/app/shared/components/nav-menu/nav-menu.component.html
src/DonateTo.WebApplication/ClientApp/src/app/shared/components/nav-menu/nav-menu.component.less

Avatar alignment
Added translate pipe in language selection

AB#659 Avatar alignment

---

src/DonateTo.WebApplication/ClientApp/src/app/home/components/donation-request/list/donation-requests-list.component.html
src/DonateTo.WebApplication/ClientApp/src/app/home/components/donation-request/list/donation-requests-list.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/home/components/donation-request/list/item/donation-requests-list-item.component.html
src/DonateTo.WebApplication/ClientApp/src/app/home/components/donation-request/list/item/donation-requests-list-item.component.less
src/DonateTo.WebApplication/ClientApp/src/app/home/components/donation-request/list/item/donation-requests-list-item.component.ts
src/DonateTo.WebApplication/ClientApp/src/app/home/home.component.html
src/DonateTo.WebApplication/ClientApp/src/app/home/home.component.ts

[AB#594](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/594)

Hover background color on 'More information' button

---

src/DonateTo.WebApplication/ClientApp/src/app/donation/donation.component.less

[AB#674](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/674)

Changed color in Yellow hearts

---

src/DonateTo.ApplicationCore/Interfaces/Repositories/IDonationRequestRepository.cs
src/DonateTo.Infrastructure/Data/Repositories/DonationRequestRepository.cs
src/DonateTo.Services/Services/DonationRequestService.cs

[AB#675](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/675)

Home page doesn't show out of date donation requests

---

src/DonateTo.Infrastructure/Data/Repositories/DonationRequestRepository.cs

[AB#675](https://dev.azure.com/AzureDevOpsSoftvision/2e5ea87f-f195-4259-8f05-e65e5f086df7/_workitems/edit/675)

Show in home donations with null finish dates
